### ISSUE TITLE
Pathex does not compile with elixir 1.14.0-rc0

### ISSUE THREAD

**Issue by ltd** [hissssst/pathex#18]
== Compilation error in file lib/pathex/accessibility.ex ==
** (ArgumentError) cannot pipe value into function.()
|> case do
  {:ok, value} -> value
  :error -> throw(:path_not_found)
end, the :|> operator can only take two arguments
    (elixir 1.14.0-rc.0) lib/macro.ex:323: Macro.pipe/3
    (elixir 1.14.0-rc.0) expanding macro: Kernel.|>/2
    lib/pathex/accessibility.ex:144: Pathex.Accessibility.from_list/2
    (elixir 1.14.0-rc.0) expanding macro: Kernel.|>/2
    lib/pathex/accessibility.ex:144: Pathex.Accessibility.from_list/2
    expanding macro: Pathex.path/2
    lib/pathex/accessibility.ex:144: Pathex.Accessibility.from_list/2

great library, this could be elixir issue

**Comment by hissssst** [comment]
Let's see how this error will behave in next candidate versions. Meanwhile, you can use 2.1 version of Pathex

**Comment by ltd** [comment]
Good news,  no compile error with 1.14.0-rc1.
